#%RAML 1.0
title: Ecyano API
version: 0.2
baseUri: https://api.e-cyanobacterium.org
mediaType: application/json
protocols: [HTTPS]
types:
### Definitions of common types
  Identifier:
    type: integer
    minimum: 1
    required: true
    example: 15
  IdentifierName:
    properties:
      id: Identifier
      name: string
  UrlIdentifierList:
    description: Multiple Identifiers separated by comma
    type: string
    required: true
    pattern: '[0-9,]+'
    example: 1,18,2
  IdentifierList:
    type: array
    items: integer
    uniqueItems: true
  IdentifierNameList:
    type: array
    items: IdentifierName
    uniqueItems: true
  OptionalIdentifier:
    type: integer
    minimum: 1
    required: false
    example: 15
  ResponseStatus:
    type: string
    enum: ['ok', 'error']
  ResponseCode:
    type: integer
    minimum: 1
    required: false
    description: Same as HTTP code or custom (700+, listed in /version/errors docs) when HTTP code is 400

### User module types //needs revision
  AuthorizationCodeRequest:
    properties:
      grant_type:
        description: Type of requested access token
        type: string
        enum: ["client_credentials", "authorization_code", "refresh_token"]
        required: true
      client_id:
        type: string
        required: true
      client_secret:
        type: string
        required: true
  RefreshCodeRequest:
    type: AuthorizationCodeRequest
    properties:
      refresh_token:
        type: string
        required: true
  PasswordCodeRequest:
    type: AuthorizationCodeRequest
    properties:
      username:
        type: string
        required: true
      password:
        type: string
        required: true
  User:
    properties:
      id: Identifier
      username:
        type: string
        required: true
      name:
        type: string
        required: true
      surname:
        type: string
        required: true
      password:
        type: string
        required: true
      type:
        type: UserType
      email: string
      groups: array
  UserType:
    properties:
      id: Identifier
      tier:
        type: integer
        required: true
      name:
        type: string
        required: true
  UserGroup:
    properties:
      id: Identifier
      name:
        type: string
        required: true
      type:
        type: integer
        required: true
      description:
        type: string
        required: true
      users:
        type: User[]
  UserGroupRole:
    properties:
      id: Identifier
      tier:
        type: integer
        required: true
      name:
        type: string
        required: true

### BCS types //needs revision
  Classification:
    properties:
      id: Identifier
      name:
        type: string
        required: true
      type:
        description: "On which type of object can this classification be used"
        type: string
        enum: ["entity", "rule"]
        required: true
  Organism:
    properties:
      id: Identifier
      name:
        type: string
        required: true
      code:
        description: User-friendly shorter version of name
        type: string
        required: true
  AbstractEntitySignature:
    properties:
      id: Identifier
      name:
        type: string
        required: true
        example: "complex of KaiB6 and KaiC6"
      code:
        description: Human-readable entity identifier, unique among all entities
        type: string
        required: true
        pattern: \w+
        example: "KaiB6C6"
      type:
        type: string
        description: Entity type, can't be changed after entity is in database
        enum: ["compartment", "complex", "structure", "atomic"]
        required: true
  ListEntitySignature:
    type: AbstractEntitySignature
    properties:
      status: ObjectStatus
  EntitySignature:
    type: AbstractEntitySignature
    properties:
      description:
        type: string
        required: false
      classifications:
        type: IdentifierList
        description: List of classification IDs
      organisms:
        type: IdentifierList
        description: List of organism IDs
  Compartment:
    type: EntitySignature
    properties:
      parent:
        description: Parent compartment ID
        type: integer
      children:
        description: Children compartment IDs
        type: IdentifierList
      components:
        description: List of Complex|Structure|Atomic entity IDs contained in this compartment
        type: IdentifierList
  Complex:
    type: EntitySignature
    properties:
      compartments:
        type: IdentifierList
        description: List of compartments
      children:
        type: IdentifierList
        description: List of child Structure/Atomic agents
  Structure:
    type: EntitySignature
    properties:
      parents:
        type: IdentifierList
        description: List of Complex parents
      children:
        type: IdentifierList
        description: List of child Atomic agents
  Atomic:
    type: EntitySignature
    properties:
      parents:
        type: IdentifierList
        description: List of Complex or Structure parents
      states: AtomicState[]
  AtomicState:
    properties:
      code:
        type: string
        description: Code of state, unique among this atomic's states
      description:
        type: string
  AllEntitySignature: Compartment | Complex | Structure | Atomic
  ListRule:
    properties:
      id: Identifier
      name:
        type: string
        description: Name of rule
      equation:
        type: string
        description: Rule in BCSL
      modifier:
        type: string
        description: Rule modifiers
      status: ObjectStatus
  Rule:
    type: ListRule
    properties:
      description:
        type: string
        description: Rule description
      classifications:
        type: IdentifierList
        description: List of classification IDs
      organisms:
        type: IdentifierList
        description: List of organism IDs
  ObjectStatus:
    type: string
    enum: ["new", "active"]
  AnnotationType:
    properties:
      name:
        type: string
        description: User-friendly database name
      code:
        type: string
        description: Database code to be used within API requests/responses

### Model types specification starts here
## First, common model types definitions
  SbmlId:
    type: string
    description: String Identifier for SBML document
  ModelStatus:
    type: string
    enum: ["new", "TBA", "active"]
  Formula:
    type: string
    description: In MathML format
  SBaseEntity:
    properties:
      id: Identifier
      sbmlId:
        type: string
        description: String Identifier for SBML document
      name:
        type: string
        required: true
      metaId:
        type: string
        description: TBA
      sboTerm:
        type: string
        description: TBA
      annotation:
        type: string
        description: TBA
      notes:
        type: string
        description: TBA
## Following types are more specific. They follow the pattern of a couple:
#1. Entity - type definition - derived from {entity}Repository
#2. EntityDetail - type definition - derived from {entity}Controller
  Model:
    type: SBaseEntity
    properties:
      userId: Identifier
      approvedId: OptionalIdentifier
      status: ModelStatus
  ModelDetail:
    type: Model
    properties:
      compartments:
        type: IdentifierNameList
      constraints:
        type: array
        items:
          properties:
            id: Identifier
            formula: Formula
      events:
        type: IdentifierNameList
      functionDefinitions:
        type: IdentifierNameList
      initialAssignments:
        type: array
        items:
          properties:
            id: Identifier
            formula: Formula
      parameters:
        type: IdentifierNameList
      reactions:
        type: IdentifierNameList
      rules:
        type: array
        items:
          properties:
            id: Identifier
            equation: Formula
      unitDefinitions:
        type: IdentifierNameList

  ModelCompartment:
    type: SBaseEntity
    properties:
        spatialDimensions: integer
        size: integer
        isConstant: boolean
  ModelCompartmentDetail:
    type: ModelCompartment
    properties:
      species:
        type: IdentifierNameList
      reactions:
        type: IdentifierNameList
      rules:
        type: array
        items:
          properties:
            id: Identifier
            equation: Formula
      unitDefinitions:
        type: IdentifierNameList

  ModelSpecie:
    type: SBaseEntity
    properties:
      initialExpression: string
      hasOnlySubstanceUnits: boolean
      isConstant: boolean
      boundaryCondition: string
  ModelSpecieDetail:
    type: ModelSpecie
    properties:
      reactionItems:
        type: IdentifierNameList
      rules:
        type: array
        items:
          properties:
            id: Identifier
            equation: Formula

  ModelReactionItem:
    type: SBaseEntity
    properties:
      type: string
      value: number
      stoichiometry: number
  ModelReactionItemDetail:
    type: ModelReactionItem
    properties:
      reactionId: Identifier
      specieId: OptionalIdentifier
      parameterId: OptionalIdentifier

  ModelReaction:
    type: SBaseEntity
    properties:
      isReversible: integer
      rate: Formula
  ModelReactionDetail:
    type: ModelReaction
    properties:
      modelId: Identifier
      compartmentId: Identifier
      reactionItems:
        type: IdentifierNameList
      functions:
        type: IdentifierNameList
      parameters:
        type: IdentifierNameList

  ModelFunction:
    properties:
      id: Identifier
      reactionId: Identifier
      name: string
      formula: string
  ModelFunctionDetail:
    type: ModelFunction

  ModelRule:
    properties:
      id: Identifier
      modelId: Identifier
  ModelRuleDetail:
    type: SBaseEntity
    properties:
      modelId: Identifier
      #specieId: OptionalIdentifier
      #compartmentId: OptionalIdentifier
      #parameterId: OptionalIdentifier
      #ruleType: string
      #equation: string

  ModelConstraint:
    type: SBaseEntity
    properties:
      modelId: Identifier
      message: string
      formula: string
  ModelConstraintDetail:
    type: ModelConstraint

  ModelEvent:
    type: SBaseEntity
    properties:
      modelId: Identifier
      trigger: string
      delay: string
      priority: string
  ModelEventDetail:
    type: ModelEvent
    properties:
      evaluateOnTrigger: boolean
      eventAssignments:
        type: array
        items:
          properties:
            id: Identifier
            formula: Formula

  ModelEventAssignment:
    type: SBaseEntity
    properties:
      formula: string
  ModelEventAssignmentDetail:
    type: ModelEventAssignment

  ModelInitialAssignment:
    type: SBaseEntity
    properties:
      #modelId: Identifier
      formula: string
  ModelInitialAssignmentDetail:
    type: ModelInitialAssignment

  ModelFunctionDefinition:
    properties:
      modelId: Identifier
      formula: string
  ModelFunctionDefinitionDetail:
    type: ModelFunctionDefinition

  ModelUnitDefinition:
    type: SBaseEntity
    properties:
      symbol: string
      compartmentId: Identifier
  ModelUnitDefinitionDetail:
    type: ModelUnitDefinition
    properties:
      units: array
      bionumbers:
        type: IdentifierNameList

  Unit:
    type: SBaseEntity
    properties:
      baseUnitId: OptionalIdentifier
      symbol: string
      exponent: number
      multiplier: number
  UnitDetail:
    type: Unit

# Bionumber entities

  Bionumber:
    properties:
      id: Identifier
      name: string
      isValid: boolean
      link: string
      userId: Identifier
      organismId: Identifier
      unitId: Identifier
      timeTo: datetime
      timeFrom: datetime
      valueTo: number
      valueFrom: number
      valueStep: number

  BionumberDetail:
    type: Bionumber
    properties:
      modelUnits:
        type: IdentifierNameList
      attributes:
        type: IdentifierNameList
      variableValues:
        type: IdentifierNameList



traits:
  Collection:
    description: Get all <<resourcePathName|!pluralize>>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              data:
                type: array
                items: <<type>>
  IdCollection:
    description: <<description>>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              data: IdentifierList
  Object:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              data:
                type: <<type>>
  ObjectList:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              data:
                type: array
                items: <<type>>
  Retrieve:
    description: Get detail of <<resourcePathName|!singularize>>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              data:
                description: <i>Known discrepancy</i> - this array always contains only one item
                type: array
                items: <<type>>
  Insert:
    description: Inserts a new <<resourcePathName|!singularize>>
    body:
      application/json:
        type: <<type>>
      application/x-www-form-urlencoded:
        type: <<type>>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              id:
                type: Identifier
                description: ID of inserted <<resourcePathName|!singularize>>
      400:
        description: Sent on bad input data
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      403:
        description: When current access token does not have necessary privileges
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      404:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      409:
        description: On duplicate unique key
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
              id:
                type: Identifier
                description: ID of already existing object
              key:
                type: string
                description: Which key was duplicated
  Update:
    description: Updates <<resourcePathName|!singularize>>
    body:
      application/json:
          type: <<type>>
      application/x-www-form-urlencoded:
        type: <<type>>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      400:
        description: Sent on bad input data
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      403:
        description: When current access token does not have necessary privileges
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      404:
        description: Object with given ID was not found
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
  Delete:
    description: Removes <<resourcePathName|!singularize>>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      403:
        description: When current access token does not have necessary privileges
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
      404:
        description: Object with given ID was not found
        body:
          application/json:
            type: object
            properties:
              status: ResponseStatus
              code: ResponseCode
  Sortable:
    queryParameters:
      sort:
        default: '[id]=asc'
        description: |
          query parameter array where keys are sort keys and values are direction (asc/desc),
          <br> possible keys: <<keys>>
        type: string
        required: false
        example: 'endpoint?sort[key1]=asc&sort[key2]=desc'
  Filterable:
    queryParameters:
      filter:
        description: |
          query parameter array where keys are filter keys and values are expressions to search for,
          <br> possible keys: any of the attributes
        type: string
        required: false
        example: 'endpoint?filter[key1]=ABC&filter[key2]=123'
  Pageable:
    queryParameters:
      perPage:
        type: integer
        description: "Number of items per page, 0 means unlimited"
        minimum: 0
        default: 0
        required: false
      page:
        description: "Current page"
        type: integer
        minimum: 1
        default: 1
        required: false
    responses:
      200:
        headers:
          X-Pages:
            description: "Will contain number of pages for given perPage value (if pagination is used)"
            type: integer
  Limitable:
    queryParameters:
      take:
        description: "How many items to return"
        type: integer
        minimum: 1
      skip:
        description: "How many items to skip"
        type: integer
        minimum: 0
        default: 0
    responses:
      200:
        headers:
          X-Count:
            description: "Will contain number of items total (if limiting is used)"
            type: integer

resourceTypes:
  _object:
    get:
      description: Get detail of <<resourcePathName|!singularize>>
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                status: ResponseStatus
                code: ResponseCode
                data:
                  description: <i>Known discrepancy</i> - this array always contains only one item
                  type: array
                  items: <<type>>
    put:
      is: [Update: {type: <<type>>}]
    delete:
      is: [Delete]

  _objectList:
    usage: Use this resourceType to represent any collection of items
    description: Get all <<resourcePathName|!pluralize>>
    get:
      description: Retrieve all <<resourcePathName|!pluralize>>
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                status: ResponseStatus
                code: ResponseCode
                data:
                  type: array
                  items: <<type>>
      is: [Sortable: {keys: <<sortBy>>}, Filterable, Pageable, Limitable]
    post:
      is: [Insert: {type: <<type>>Detail}]

  EntityList:
    get:
      is: [Collection: {type: <<type>>}, Sortable: {keys: 'id, name, type, code'}, Pageable, Limitable]
      description: List of EntitySignatures of type <<type>>
      queryParameters:
        annotation:
          type: string
          description: Filter entities by annotation, format TYPE:ID, where type is one of supported annotation types
          example: 'KEGG:CP123'
          pattern: .+:.+
        name:
          type: string
          description: Filter entities by part of name, "clever" search may be used
  EntitySetStatus:
    post:
      description: Changes status of <<name>>, users may not have privileges
      body:
        application/json:
          properties:
            status: ObjectStatus
        application/x-www-form-urlencoded:
          properties:
            status: ObjectStatus
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                status: ResponseStatus
                code: ResponseCode

/version:
  description: Information about API version
  get:
    responses:
      200:
        body:
          application/json:
            properties:
              status: ResponseStatus
              code: ResponseCode
              data:
                properties:
                  version:
                    type: string
  /errors:
    description: |
      Any error code not listed bellow shall never be encountered by users of this API.
      With custom error codes (700+), HTTP code will be 400 Bad Request.

      List of error codes (!! INCOMPLETE !! - more will be added later, as API is under construction now):
      [Code (Http code) - Description]
      401 (401 Unauthorized) - Unauthorized request, will be implemented with authentication support.
      403 (403 Forbidden)
      404 (404 Not Found) - Requested resource was not found
      409 (409 Conflict) - Request not allowed in current state of the resource
      500 (500 Internal Server Error) - Server-side or application error. Please, report these!
      700 - Attempting to access non-existing object
      701 - When saving an object (POST, PUT methods) and some
      702 - Invalid argument
      703 - Invalid field specified for sort

      BCS - Entity Signature errors:
      710 - Invalid entity specified as location (must be Compartment), error details: {given: given type}
      711 - Invalid entity specified as parent, error details: {parent: parent type, child: child type}

#Authorization
/authorize:
  description: Authorization endpoint
  post:
    is: [Insert: {type: AuthorizationCodeRequest}]
/users:
  description: Users endpoint
  get:
    is: [Collection: {type: User}]
  post:
    is: [Insert: {type: User}]
  /{id}:
    uriParameters:
      id:
        UrlIdentifierList
    type: {_object: {type: User}}
/user:
  description: Returns detail on user depending on the Bearer access token
  type: {_object: {type: User}}


/userTypes:
  description: Types of user group roles endpoint
  get:
    is: [Collection: {type: UserType}]
  /{id}:
    uriParameters:
      id:
        UrlIdentifierList
    get:
      is: [Retrieve: {type: UserType}]
/userGroups:
  description: User group endpoint
  get:
    is: [Collection: {type: UserGroup}]
  post:
    is: [Insert: {type: UserGroup}]
  /{id}:
    uriParameters:
      id:
        UrlIdentifierList
    get:
      is: [Retrieve: {type: UserGroup}]
    put:
      is: [Update: {type: UserGroup}]
    delete:
      is: [Delete]
/userGroupRoles:
  description: Types of user group roles endpoint
  get:
    is: [Collection: {type: UserGroupRole}]
  /{id}:
    uriParameters:
      id:
        UrlIdentifierList
    get:
      is: [Retrieve: {type: UserGroupRole}]
#BCS
/annotations:
  /types:
    description: List of valid annotation term types - databases
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                status: ResponseStatus
                code: ResponseCode
                data:
                  type: AnnotationType[]
  /link:
    /{type}:
      uriParameters:
        type: string
      description: Generate link to particular database from ID
      get:
        queryParameters:
          id:
            type: string
        responses:
          200:
            body:
              application/json:
                properties:
                  status: ResponseStatus
                  code: ResponseCode
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        description: URL address of object defined by parameter ID in database {type}

/classifications:
  get:
    is: [Collection: {type: Classification}, Sortable: {keys: 'id, name'}, Pageable, Limitable]
  post:
    is: [Insert: {type: Classification}]
  /{id}:
    uriParameters:
      id:
        UrlIdentifierList
    get:
      is: [ObjectList: {type: Classification}]
    put:
      is: [Update: {type: Classification}]
    delete:
      is: [Delete]
  /{type}:
    uriParameters:
      type:
        type: string
        enum: [entity, rule]

/organisms:
  get:
    is: [Collection: {type: Organism}, Sortable: {keys: 'id, name, type'}, Pageable, Limitable]
  post:
    is: [Insert: {type: Organism}]
  /{id}:
    uriParameters:
      id:
        UrlIdentifierList
    get:
      is: [ObjectList: {type: Organism}]
    put:
      is: [Update: {type: Organism}]
    delete:
      is: [Delete]

/entities:
  description: Entity Signatures
  type: {EntityList: {type: ListEntitySignature}}
  get:
    is: [Sortable: {keys: "id, name, code, type"}]
  post:
    is: [Insert: {type: AllEntitySignature}]
  /{id}:
    uriParameters:
      id:
        type: UrlIdentifierList
    get:
      description: Get specific compartment
      is: [ObjectList: {type: AllEntitySignature}]
    put:
      is: [Update: {type: AllEntitySignature}]
    delete:
      is: [Delete]
  /{code}:
    uriParameters:
      code:
        type: string
        pattern: \w+
        description: 'Entity code'
    get:
      description: Get specific entity by code
      is: [Object: {type: AllEntitySignature}]
  /status:
    type: {EntitySetStatus: {name: "entity"}}
#    /compartment:
#      type: {EntityList: {type: Compartment}}
#    /complex:
#      type: {EntityList: {type: Complex}}
#    /structure:
#      type: {EntityList: {type: Structure}}
#    /atomic:
#      type: {EntityList: {type: Atomic}}

/rules:
  get:
    is: [Collection: {type: ListRule}, Sortable: {keys: 'id, name, code'}, Pageable, Limitable]
  post:
    is: [Insert: {type: Rule}]
  put:
    is: [Update: {type: Rule}]
  delete:
    is: [Delete]
  /{id}:
    uriParameters:
      id:
        type: UrlIdentifierList
    get:
      is: [ObjectList: {type: Rule}]
    /reactants:
      get:
        is: [IdCollection: {description: Get all products of this rule}]
      /products:
        get:
          is: [IdCollection: {description: Get all products of this rule}]

# Models

/models:
  type: {_objectList: {type: Model, "sortBy" : "id, name, userId, approvedId, status"} }
  /{id}:
    type: {_object: {type: ModelDetail}}
    /compartments:
      type: {_objectList: {type: ModelCompartment, "sortBy" : 'id, name, modelId'} }
      /{id}:
        type: {_object: {type: ModelCompartmentDetail}}
        /species:
          type: {_objectList: {type: ModelSpecie, "sortBy" : 'id, modelId'} }
          /{id}:
            type: {_object: {type: ModelSpecieDetail}}
            /reactionItems:
              type: {_objectList: {type: ModelReactionItem, "sortBy" : 'id, name'} }
              /{id}:
                type: {_object: {type: ModelReactionItemDetail}}
    /reactions:
      type: {_objectList: {type: ModelReaction, "sortBy" : 'id, name'} }
      /{id}:
        type: {_object: {type: ModelReactionDetail}}
        /reactionItems:
          type: {_objectList: {type: ModelReactionItem, "sortBy" : 'id, name'} }
          /{id}:
            type: {_object: {type: ModelReactionItemDetail}}
        /functions:
          type: {_objectList: {type: ModelFunction, "sortBy" : 'id, name'}}
          /{id}:
            type: {_object: {type: ModelFunctionDetail}}
    /constraints:
      type: {_objectList: {type: ModelConstraint, "sortBy" : 'id, name'} }
      /{id}:
        type: {_object: {type: ModelConstraintDetail}}
    /events:
      type: {_objectList: {type: ModelEvent, "sortBy" : 'id, name'} }
      /{id}:
        type: {_object: {type: ModelEventDetail}}
      /eventAssignments:
        type: {_objectList: {type: ModelEventAssignment, "sortBy" : 'id, name, modelId'} }
        /{id}:
          type: {_object: {type: ModelEventAssignmentDetail}}
    /initialAssignments:
      type: {_objectList: {type: ModelInitialAssignment, "sortBy" : 'id, modelId'} }
      /{id}:
        type: {_object: {type: ModelInitialAssignmentDetail}}
    /functionDefinitions:
      type: {_objectList: {type: ModelFunctionDefinition, "sortBy" : 'id, modelId'} }
      /{id}:
        type: {_object: {type: ModelFunctionDefinitionDetail}}
    /rules:
      type: {_objectList: {type: ModelRule, "sortBy" : 'id, modelId'} }
      /{id}:
        type: {_object: {type: ModelRuleDetail}}
    /unitDefinitions:
      type: {_objectList: {type: ModelUnitDefinition, "sortBy" : 'id, modelId'} }
      /{id}:
        type: {_object: {type: ModelUnitDefinitionDetail}}

/units:
  type: {_objectList: {type: Unit, "sortBy" : 'id, name'} }
  /{id}:
    type: {_object: {type: UnitDetail}}

/bionumber:
  type: {_objectList: {type: Bionumber, "sortBy" : 'id'} }
  /{id}:
    type: {_object: {type: BionumberDetail}}
